/**
 * Mock student data for prototype — Faculty of Science, University of Kelaniya
 */
window.PORTAL_DATA = {
  student: {
    name: "K. D. Perera",
    id: "2021/FS/C/0456",
    programme: "B.Sc. (Hons) in Computer Science",
    registrationYear: "2021/2022",
    academicYear: "2024/2025",
    examStatus: "Eligible for semester examinations",
    currentGpa: "3.52",
    totalCredits: 96,
    nonGpaCredits: 6,
  },
  resultsByYear: {
    1: {
      label: "Year 1 Results",
      gpa: "3.45",
      totalCredits: 30,
      nonGpaCredits: 2,
      rows: [
        {
          code: "FS101",
          name: "Fundamentals of Science",
          acYear: "2021/2022",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "B+",
        },
        {
          code: "FS102",
          name: "Communication Skills",
          acYear: "2021/2022",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "A-",
        },
        {
          code: "CS111",
          name: "Introduction to Programming",
          acYear: "2021/2022",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "A",
        },
        {
          code: "MT112",
          name: "Calculus for Science",
          acYear: "2021/2022",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "B",
        },
        {
          code: "CH121",
          name: "General Chemistry I",
          acYear: "2021/2022",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "B+",
        },
        {
          code: "PHY131",
          name: "Mechanics & Waves",
          acYear: "2021/2022",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "B",
        },
      ],
    },
    2: {
      label: "Year 2 Results",
      gpa: "3.48",
      totalCredits: 32,
      nonGpaCredits: 2,
      rows: [
        {
          code: "CS211",
          name: "Data Structures",
          acYear: "2022/2023",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "A-",
        },
        {
          code: "CS212",
          name: "Database Systems",
          acYear: "2022/2023",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "B+",
        },
        {
          code: "ST221",
          name: "Probability & Statistics",
          acYear: "2022/2023",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "B+",
        },
        {
          code: "CS213",
          name: "Computer Organisation",
          acYear: "2022/2023",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "B",
        },
      ],
    },
    3: {
      label: "Year 3 Results",
      gpa: "3.55",
      totalCredits: 34,
      nonGpaCredits: 2,
      rows: [
        {
          code: "CS311",
          name: "Software Engineering",
          acYear: "2023/2024",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "A",
        },
        {
          code: "CS312",
          name: "Operating Systems",
          acYear: "2023/2024",
          attempt: "1",
          status: "Completed",
          note: "—",
          grade: "A-",
        },
        {
          code: "CS313",
          name: "Computer Networks",
          acYear: "2023/2024",
          attempt: "1",
          status: "Pending",
          note: "Awaiting final board",
          grade: "—",
        },
      ],
    },
    4: {
      label: "Year 4 Results",
      gpa: "—",
      totalCredits: 0,
      nonGpaCredits: 0,
      rows: [],
    },
  },
  admission: {
    examPeriod: "Second Semester Examinations — 2024/2025",
    centreName: "Faculty of Science Examination Hall — Block B",
    centreAddress: "University of Kelaniya, Dalugama, Kelaniya 11600",
    validFrom: "15 April 2026",
    validTo: "30 April 2026",
    instructions:
      "Bring this card and a valid university ID. Arrive 30 minutes before the scheduled time.",
  },
};
